# Generated by Django 6.0 on 2025-12-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_avatar_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.jpg", upload_to="avatars/"
            ),
        ),
    ]
